---
- hosts: 172.31.9.2
  become: yes
  tasks:
    - name: I want to run linux command on node
      command: hostname -f
      register: myresult

    - name: I want to display linux command output
      debug:
        msg: "{{myresult}}"