---
- hosts: 172.31.9.2
  become: yes
  tasks:
    - include_tasks: myfile.yml

    - name: I want to install apache2
      apt:
        name: apache2
        state: present

    - name: I want to replace apache2 with my jinja template
      template:
        src: demo.html
        dest: /var/www/html/index.html