---
- hosts: webservers
  become: yes
  tasks:
          - name: I want to install java jdk8 on ubuntu server
            apt:
                    name: openjdk-8-jre
                    state: present
            when: ansible_os_family == "Debian"

          - name: I want to install java jdk8 on RedHat server
                    name: java-1.8.0-openjdk
                    state: present
            when: ansible_os_family == "RedHat"