---
- hosts: webservers
  become: yes
  tasks:
          - name: I want to install apache2 in ubuntu ansible node 1
            apt:
                    name: apache2
                    state: present
            when: ansible_os_family == "Debian"

          - name: I want to install apache2 in redhat node 2
            yum:
                    name: httpd
                    state: present
            when: ansible_os_family == "RedHat"